# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finishdassigmentsui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, completed_MainWindow):
        completed_MainWindow.setObjectName("completed_MainWindow")
        completed_MainWindow.setGeometry(QtCore.QRect(0, 0, 1085, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        completed_MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(completed_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1085, 650))
        self.widget.setObjectName("widget")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1085, 650))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bg = QtWidgets.QLabel(self.frame)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1085, 650))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("../resources/bg.jpg"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(325, 0, 451, 111))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_2 = QtWidgets.QLabel(self.frame_2)
        self.title_2.setText("")
        self.title_2.setPixmap(QtGui.QPixmap("../resources/finished_assignments.png"))
        self.title_2.setScaledContents(True)
        self.title_2.setObjectName("title_2")
        self.horizontalLayout.addWidget(self.title_2)
        self.complete_table = QtWidgets.QTableWidget(self.frame)
        self.complete_table.setGeometry(QtCore.QRect(50, 140, 651, 471))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.complete_table.setFont(font)
        self.complete_table.setStyleSheet(" background-color: transparent;")
        self.complete_table.setDragEnabled(False)
        self.complete_table.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.complete_table.setObjectName("complete_table")
        self.complete_table.setColumnCount(3)
        self.complete_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.complete_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.complete_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.complete_table.setHorizontalHeaderItem(2, item)
        self.complete_table.horizontalHeader().setDefaultSectionSize(180)
        self.delete_2 = QtWidgets.QPushButton(self.frame)
        self.delete_2.setGeometry(QtCore.QRect(800, 330, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid black;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 255, 50);\n"
"    border: 2px solid #000080;\n"
"    transition: background-color 0.3s, border 0.3s;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/deleteic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_2.setIcon(icon1)
        self.delete_2.setIconSize(QtCore.QSize(35, 35))
        self.delete_2.setObjectName("delete_2")
        completed_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(completed_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(completed_MainWindow)

    def retranslateUi(self, completed_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        completed_MainWindow.setWindowTitle(_translate("MainWindow", "Completed Tasks"))
        item = self.complete_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Completed Tasks"))
        item = self.complete_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time Of Completion"))
        item = self.complete_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date Of Completition"))
        self.delete_2.setText(_translate("MainWindow", " Delete Task"))
